In [24]:
import pdfplumber
import pandas as pd

In [4]:
pdf=pdfplumber.open("moe_report.pdf")

In [65]:
tables_array = []
for page in range(len(pdf.pages)):
    p0 = pdf.pages[page]
    #im = p0.to_image()
    tables=p0.extract_tables()
    if tables:
        for sublist in tables:
            if sublist:
                tables_array.append(sublist)

In [72]:
tables_array[4]

[['Mall of the Emirates: Secondary Trade Area Overview',
  None,
  None,
  None,
  None,
  None,
  None],
 ['STA',
  'Q3 Yr 2020',
  'Q1 Yr 2021',
  'Q3 Yr 2021',
  'Q1 Yr 2022',
  'Q3 Yr 2022',
  'Year on Year\nChange %\n(Q1 Yr 2022 -Yr\nQ3 2022)'],
 ['% of Shoppers', '4.7%', '5.6%', '5.3%', '4.8%', '4.5%', '-0.3%'],
 ['Sales Contribution', '3.3%', '3.8%', '3.5%', '3.1%', '3.0%', '-0.2%'],
 ['Population', '308,005', '310,400', '311,700', '313,920', '316,210', '0.7%'],
 ['Households', '75,763', '79,520', '80,007', '80,571', '80,305', '-0.3%'],
 ['Average Monthly HHI (AED)',
  '26,200',
  '24,600',
  '24,700',
  '24,800',
  '26,100',
  '5.2%'],
 ['Visit Frequency', '33.0', '36.8', '39.4', '41.7', '42.0', '0.8%'],
 ['Avg Household Size', '4.1', '3.9', '3.9', '3.9', '3.9', '1.1%'],
 ['Dwell Time (minutes)', '125', '147', '151', '161', '168', '4.2%'],
 ['Average Age', '31.2', '32.9', '31.2', '31.7', '31.9', '0.6%']]

In [17]:
tables=p0.extract_tables()

In [29]:
pd.DataFrame(tables[0][2:], columns=tables[0][1])

,Indicators,Yr 2015,Yr 2016,Yr 2017,Yr 2018,Yr 2019,Yr 2020,Q1 Yr 2021,Q3 Yr 2021,Q1 Yr 2022,Q3 Yr 2022,CAGR ('15 -22)
0,Dubai Population,"2,408,200","2,565,100","2,629,100","2,672,900","2,690,100","2,436,089","2,470,200","2,500,100","2,554,450","2,605,300",1.1%
1,Population Growth %,7.4%,6.5%,2.5%,1.7%,0.6%,-9.4%,1.4%,1.2%,2.2%,2.0%,N/A
2,Dubai GDP at Current Prices (in\nMillion AED),"386,500","398,459","414,357","424,134","436,345","374,000","410,400",None,"472,800",None,2.9%
3,GDP Growth %,5.0%,3.1%,4.0%,2.4%,2.9%,-14.3%,9.7%,None,15.2%,None,N/A
4,Dubai GDP per Capita (AED),"160,490","155,340","157,600","158,680","162,200","153,520","164,150",None,"181,480",None,1.8%
5,Dubai Mall GLA sqm,"2,738,955","3,174,300","3,254,500","3,251,700","3,763,000","3,859,500","4,070,200",None,"4,232,700","4,326,560",6.7%
6,Dubai Mall GLA per Capita,1.14,1.24,1.24,1.22,1.40,1.58,1.65,1.63,1.66,1.66,5.6%
7,Dubai Visitors,"14,200,000","14,900,000","15,790,000","15,920,000","16,730,000","5,241,000","7,280,000",None,"15,300,000",None,1.1%
8,Tourist Growth %,7.6%,4.9%,6.0%,0.8%,5.1%,-68.7%,38.9%,None,110.2%,None,N/A